name: Build & Release Intuis Connect


permissions:
  contents: write     # <-- allows tag & release creation
  packages: read      # (optional) keep default read on packages

on:
  push:
    branches: [ master, main ]          # trigger on default branch
    paths:
      - 'custom_components/intuis_connect/**'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # 1 ─ Checkout full history (tags included)
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2 ─ Extract version from manifest.json
    - name: Extract integration version
      id: vars
      run: |
        VERSION=$(jq -r '.version' custom_components/intuis_connect/manifest.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    # 3 ─ Create release ZIP
    - name: Build ZIP package
      run: |
        zip -r intuis_connect_${{ steps.vars.outputs.version }}.zip custom_components/intuis_connect

    # 4 ─ Create (or reuse) Git tag v<version>
    - name: Create tag if needed
      id: tag
      env:
        VERSION: ${{ steps.vars.outputs.version }}
      run: |
        TAG="${VERSION}"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        if git rev-parse "$TAG" >/dev/null 2>&1; then
          echo "Tag $TAG already exists."
        else
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"
          git tag "$TAG"
          git push origin "$TAG"
        fi

    # 5 ─ Create / update the GitHub Release and upload the asset
    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        name: ${{ steps.vars.outputs.version }}
        draft: false
        prerelease: false
        files: intuis_connect_${{ steps.vars.outputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
